### ISSUE TITLE
Components > Response Field

### ISSUE THREAD

**Issue by anneguo3** [nwplus/admin#115] opened 2021-11-07 01:24 UTC
Read-only field, ability to specify that it is a link

<img width="422" alt="Screen Shot 2021-11-06 at 9 24 15 PM" src="https://user-images.githubusercontent.com/40816838/140628785-52ae122b-d631-466d-a45a-ee4e3676dfa5.png">

**Comment by andykwan1124** [comment] 2021-12-03 03:46
Closed for duplicate of #101

**Closed by andykwan1124** 2021-12-03 03:47 UTC
Labels: hacker_assessment_2021
